version: "3"

services:
  master:
    image: redis:5

  slave-1:
    image: redis:5
    command: redis-server --slaveof redis-master 6379
    links:
      - master:redis-master

  slave-2:
    image: redis:5
    command: redis-server --slaveof redis-master 6379
    links:
      - master:redis-master

  sentinel-1:
    image: redis:5
    command: redis-server /etc/redis/sentinel.conf --sentinel
    volumes:
      - ./sentinel-1:/etc/redis/
    depends_on:
      - master
      - slave-1
      - slave-2

  sentinel-2:
    image: redis:5
    command: redis-server /etc/redis/sentinel.conf --sentinel
    volumes:
      - ./sentinel-2:/etc/redis/
    depends_on:
      - master
      - slave-1
      - slave-2

  sentinel-3:
    image: redis:5
    command: redis-server /etc/redis/sentinel.conf --sentinel
    volumes:
      - ./sentinel-3:/etc/redis/
    depends_on:
      - master
      - slave-1
      - slave-2
